[package]
name = "ruspy_parser"
version = "0.1.0"
authors = ["Keiv <keiv-fly@github.com>"]
edition = "2018"
build = "build.rs" # LALRPOP preprocessing

[dependencies]
regex = "1"
lalrpop-util = "0"

[build-dependencies]
lalrpop = "0"